# TODO: check remaining controllers in every service
server:
  port: 8088

routes:
  auth: http://localhost:8080
  courier: http://localhost:8081
  warehouse: http://localhost:8082
  erp: http://localhost:8083
  order: http://localhost:8084
  cart: http://localhost:8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: courier-route
          uri: ${routes.courier}
          predicates:
            - Path=/api/couriers/**
        - id: delivery-route
          uri: ${routes.courier}
          predicates:
            - Path=/api/delivery-tasks/**
        - id: warehouse-route
          uri: ${routes.warehouse}
          predicates:
            - Path=/api/warehouse/**
        - id: cart-route
          uri: ${routes.cart}
          predicates:
            - Path=/api/carts/**
        - id: order-route
          uri: ${routes.order}
          predicates:
            - Path=/api/orders/**
        - id: user-route
          uri: ${routes.auth}
          predicates:
            - Path=/api/users/**
        - id: admin-route
          uri: ${routes.auth}
          predicates:
            - Path=/api/admins/**
        - id: auth-route
          uri: ${routes.auth}
          predicates:
            - Path=/api/auth/**



