server:
  port: 8088

routes:
  auth: http://localhost:8080
  courier: http://localhost:8081
  warehouse: http://localhost:8082
  erp: http://localhost:8083
  order: http://localhost:8084
  cart: http://localhost:8085

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: courier-route
          uri: ${routes.courier}
          predicates:
            - Path=/api/couriers/**
        - id: delivery-route
          uri: ${routes.courier}
          predicates:
            - Path=/api/delivery-tasks/**
        - id: packagers-route
          uri: ${routes.warehouse}
          predicates:
            - Path=/api/packagers/**
        - id: assign-route
          uri: ${routes.warehouse}
          predicates:
            - Path=/api/assign/**
        - id: seed-route
          uri: ${routes.warehouse}
          predicates:
              - Path=/api/seed/**
        - id: warehouse-manager-route
          uri: ${routes.warehouse}
          predicates:
            - Path=/api/warehouse/manager/**
        - id: package-route
          uri: ${routes.warehouse}
          predicates:
            - Path=/api/package/**
        - id: stock-route
          uri: ${routes.warehouse}
          predicates:
            - Path=/api/stock/**
        - id: cart-route
          uri: ${routes.cart}
          predicates:
            - Path=/api/carts/**
        - id: order-route
          uri: ${routes.order}
          predicates:
            - Path=/api/orders/**
        - id: user-route
          uri: ${routes.auth}
          predicates:
            - Path=/api/users/**
        - id: admin-route
          uri: ${routes.auth}
          predicates:
            - Path=/api/admins/**
        - id: auth-route
          uri: ${routes.auth}
          predicates:
            - Path=/api/auth/**
        - id: courier-analytics-route
          uri: ${routes.erp}
          predicates:
            - Path=/api/courier-analytics/**
        - id: customer-analytics-route
          uri: ${routes.erp}
          predicates:
            - Path=/api/customer-analytics/**
        - id: fulfillment-analytics-route
          uri: ${routes.erp}
          predicates:
            - Path=/api/fulfillment-analytics/**
        - id: inventory-analytics-route
          uri: ${routes.erp}
          predicates:
            - Path=/api/inventory-analytics/**
        - id: order-analytics-route
          uri: ${routes.erp}
          predicates:
            - Path=/api/order-analytics/**
        - id: product-analytics-route
          uri: ${routes.erp}
          predicates:
            - Path=/api/product-analytics/**
        - id: profit-analytics-route
          uri: ${routes.erp}
          predicates:
            - Path=/api/profit-analytics/**
        - id: revenue-analytics-route
          uri: ${routes.erp}
          predicates:
            - Path=/api/revenue-analytics/**




